project:
  type: website

website:
  title: "Virtual Production Dashboard"
  navbar:
    left:
      - href: index.qmd
        text: Data View
      - href: plots.qmd
        text: Plot View

format:
  dashboard:
    orientation: rows
    theme: cosmo

execute:
  freeze: auto
